### PR TITLE
Fix Nether and End portals for non-player entities

### PR DESCRIPTION
**Pull request by alexthvest**
I tried to fix problems with non-player entities and portals cause some will need this functionallity on their server (like we're).

The main problem I found that teleportation ticked on ServerLevel tick thread but entities neeed to check Poi in another world. I use taskScheduler to schedule changeDimension on main thread.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Instead of creating a new patch, it would be better to amend the `0018-Parallel-world-ticking.patch` patch.

It would also be nice to see how Folia handles entity teleport between worlds, iirc Folia completly changes how portal teleports work but yeah, another fix is to just schedule entity moves to be handled after the worlds are ticked.

**Comment by Potothingi** [comment]
Hello. When will this be resolved?

**Comment by DaddyRobLIVE** [comment]
Any update here? I think this is an important vanilla feature.

**Comment by Potothingi** [comment]
I can't apply this change in 1.21.1. The portal code has changed a lot. What should I do?

**Comment by Potothingi** [comment]
https://github.com/SparklyPower/SparklyPaper/pull/34

**Pull request closed without merging**
